# Generated by Django 4.0.6 on 2022-07-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.timestampmodel')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
            bases=('users.timestampmodel',),
        ),
    ]
